#!/usr/bin/env bash

dir=$1
if [[ -z "$1" ]]; then
	dir=$HOME
fi

selected=$(fd -H . $dir -d 1 | fzf)
if [[ -z "$selected" ]]; then
	exit 0
fi

selected_name=$(basename $selected | tr ":,. " "____")

switch_to() {
	if [[ -z "$ZELLIJ" ]]; then
        #TODO 
        echo zellij is missing
	else
		zellij a $selected_name
	fi

}

if zellij list-sessions | grep -q $selected_name; then
    zellij a $selected_name
else
    zellij -s $selected_name
fi

